services:

  api:
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "3000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - fullstack-net
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgadmin:
