FROM node:latest AS build
WORKDIR /app
RUN apt-get update && apt-get install -y default-jre
RUN npm install -g @angular/cli
RUN npm install @openapitools/openapi-generator-cli -g
COPY package*.json ./
RUN npm install
COPY . .
ARG CACHEBUST=null
RUN echo $CACHEBUST
RUN curl -sf http://host.docker.internal:8080/v3/api-docs -o /tmp/openapi.json
RUN openapi-generator-cli generate \
  -i /tmp/openapi.json \
  -g typescript-angular \
  -o src/app/api \
  --skip-validate-spec
RUN ng build --configuration=production

FROM nginx:latest AS runtime
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build app/dist/ui/browser /usr/share/nginx/html
EXPOSE 80
