FROM node:latest AS build
WORKDIR /app
RUN npm install -g @angular/cli
COPY package*.json ./
RUN npm install
COPY . .
RUN ng build --configuration=production

FROM nginx:latest AS runtime
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build app/dist/ui/browser /usr/share/nginx/html
EXPOSE 80
