FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY mvnw ./
COPY .mvn .mvn
COPY pom.xml ./
RUN ./mvnw -B -Pprod dependency:go-offline
RUN ./mvnw -B -Pprod dependency:resolve dependency:resolve-plugins
COPY checkstyle.xml ./
COPY src src
RUN ./mvnw -B -Pprod \
    resources:resources \
    compiler:compile \
    jar:jar \
    spring-boot:repackage

FROM eclipse-temurin:17-jre AS runtime
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "app.jar"]
