name: Build UI

on:
  workflow_call:

jobs:
  build-ui:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: db_user
          POSTGRES_PASSWORD: db_pass
        options: >-
          --health-cmd "bash -c 'pg_isready -h localhost -U $POSTGRES_USER'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Cache Node Modules
      id: cache-npm
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-ci-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-ci-${{ env.cache-name }}-
          ${{ runner.os }}-ci-
          ${{ runner.os }}-

    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      working-directory: ./ui
      name: List State of Node Modules
      continue-on-error: true
      run: npm list

    - name: Install Dependencies
      working-directory: ./ui
      run: |
        npm install -g @angular/cli
        npm install

    - name: OpenAPI typescript
      uses: actions/download-artifact@v4
      with:
        name: openapi-typescript
        path: ui/src/app/api

    - name: Build UI
      working-directory: ./ui
      run: |
        ng build --configuration=production

    - name: Upload UI
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ui-app
        path: ui/dist/ui/browser
