name: Main

on:
  workflow_dispatch:
  push:
    branches:
    - '**'

jobs:
  maven-cache:
    uses: ./.github/workflows/maven-cache.yml

  openapi-build:
    needs: maven-cache
    uses: ./.github/workflows/openapi-build.yml

  api-check:
    needs:
      - maven-cache
    uses: ./.github/workflows/api-check.yml

  api-test:
    needs:
      - maven-cache
      - openapi-build
    uses: ./.github/workflows/api-test.yml

  api-build:
    needs:
      - maven-cache
    uses: ./.github/workflows/api-build.yml

  ui-check:
    uses: ./.github/workflows/ui-check.yml

  ui-test:
    needs:
      - openapi-build
      - api-build
    uses: ./.github/workflows/ui-test.yml

  ui-build:
    needs: openapi-build
    uses: ./.github/workflows/ui-build.yml

  deploy-pages:
    needs:
      - openapi-build
      - api-test
      - ui-test
    uses: ./.github/workflows/deploy-pages.yml
